title: jsonapi-resolvers
description: Resolve JSON-API entities
baseurl: /jsonapi-resolvers
repository: someimportantcompany/jsonapi-resolvers

remote_theme: someimportantcompany/jekyll-documentation
permalink: pretty
